name: workflow
on: [push]
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v1
      - name: Prepare
        run: npm ci
      - name: Lint
        uses: stiesssh/tslint-actions@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pattern: 'files/*.ts'
      - name: Build
        run: npm run build
